-- 뿌리기 TBL (SPREAD) 생성

CREATE TABLE SPREAD
(
    ID INT AUTO_INCREMENT 
    , TOKEN VARCHAR(3)
    , SPREAD_USER_ID INT
    , CHAT_ROOM_ID INT
    , SPREAD_TIME TIMESTAMP DEFAULT NOW()
    , SPREAD_TOTAL_MONEY INT
    , PRIMARY KEY(ID)
    , UNIQUE KEY(TOKEN)
);

-- 채팅방 TBL (CHAT_ROOM) 생성

CREATE TABLE CHAT_ROOM
(
    ID INT AUTO_INCREMENT
    , CHAT_ROOM_ID INT
    , USER_ID INT
    , PRIMARY KEY(ID)
);

-- 채팅방 인덱스
CREATE INDEX CHAT_ROOM_IDX ON CHAT_ROOM(CHAT_ROOM_ID)

-- 받기 내역 TBL (RECEIVE_STATEMENT) 생성
CREATE TABLE RECEIVE_STATEMENT
(
    ID INT AUTO_INCREMENT
    , TOKEN VARCHAR(3)
    , RECEIVE_INDEX INT
    , RECEIVE_MONEY INT
    , RECEIVE_USER_ID INT
    , PRIMARY KEY(ID)
    , UNIQUE KEY(TOKEN, RECEIVE_INDEX)
);